[package]
name = "ssq"
version = "0.1.0"
authors = ["Maix0 <maix522@gmail.com>"]
edition = "2018"
lisence = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
ssq-sys = { path = "../ssq_sys" }
